rails_overflow/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get   'login' =>  'sessions#new'
  post  'login' =>  'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :questions do
    resources :answers
  end

  root 'welcome#index'

end

rails_overflow/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  # belongs_to :user
end

rails_overflow/app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  has_many :answers, dependent: :destroy
  attr_accessor :text

  def tags
    text
  end

  def tags=(input)
    self.text = input
  end


end

rails_overflow/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt
  validates :email, presence: true, uniqueness: true
  has_many  :questions
  has_many :answers

  def password
    @password ||= Password.new(hashed_password)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.hashed_password = @password
  end

  def authenticate(pass_to_check)

    if self.password == pass_to_check
      return true
    else
      return nil
    end
  end


end

rails_overflow/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  private
    def answer_params
      params.require(:answer).permit(:user, :body)
    end
end

rails_overflow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_overflow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :text)
    end
end

rails_overflow/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end


  def current_user
    User.find_by(id: session[:user_id])
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]
    @user = User.find_by(email: email)

    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      p session[:user_id]
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def destroy
    p session[:user_id]
    session.delete(:user_id)
    @current_user = nil
    redirect_to questions_path
  end
end

rails_overflow/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    p user_params[:password]
    @user.password = user_params[:hashed_password]
    @user.save!
    redirect_to questions_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :hashed_password)
    end
end

rails_overflow/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails_overflow/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_overflow/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    puts session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session[:user_id]
    session.delete(:user_id)
    @current_user = nil
  end
end

rails_overflow/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails_overflow/app/views/answers/_answer.html.erb
<p>
  <strong>Answer:</strong>
  <%= answer.body %>
</p>

<p>
  <%= link_to 'Destroy Answer', [answer.question, answer],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

rails_overflow/app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

rails_overflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails_overflow/app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

rails_overflow/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

rails_overflow/app/views/questions/index.html.erb
<h1>List of All Questions</h1>

<%= link_to 'New question', new_question_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @questions.each do |question| %>
  <tr>
    <td><%=question.title %></td>
    <td><%=question.text %></td>
    <td><%= link_to 'Show', question_path(question) %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question_path(question),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %></td>
  </tr>
  <% end%>
</table>
<%= link_to 'New User', new_user_path %>

<% if current_user == nil %>
<%= link_to 'Log In', login_path %>
<% else %>
<%= link_to 'Log Out', logout_path, method: "delete" %>
<% end %>

rails_overflow/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

rails_overflow/app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<h2>Answers</h2>
<%= render @question.answers %>


<h2>Add an answer:</h2>
<%= render 'answers/form' %>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

rails_overflow/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
    </h2>
    <ul>
      <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <%end%>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :hashed_password%><br>
  <%= f.text_field :hashed_password%>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

rails_overflow/app/views/users/new.html.erb
<h1>Register!</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

rails_overflow/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'questions' %>